name: Build, Push and Deploy Docker Image
run-name: Build, Push and Deploy Image

on: [push]

env:
  IMAGE_NAME: "ghcr.io/ilhamellyanawa/nginx-ilhamellya"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t $IMAGE_NAME .

      - name: List Image
        run: docker images

      - name: Login to GitHub Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u ilhamellyanawa --password-stdin

      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u ilhamellyanawa --password-stdin

      - name: Stop and remove existing container
        run: docker compose down --rmi all

      - name: Start container
        run: docker compose up -d

      - name: View container
        run: docker compose ps

      - name: Check container response
        run: curl localhost:8080
